def registry = 'https://nguyentiennghi212952019.jfrog.io'

pipeline {
    agent {
        node {
            label 'jenkinsslave'
        }
    }
    environment {
        MAVEN_HOME = "/opt/apache-maven-3.9.9"  // Path to Maven installation
        PATH = "/usr/bin/git:/usr/bin/bash/:/opt/apache-maven-3.9.9/bin"  // Ensure Maven is in the PATH
    }
    stages {
        stage('Install Coreutils') {
            steps {
                script {
                    // Installing coreutils on the agent
                    sh 'sudo apt-get update && sudo apt-get install -y coreutils'  // For Ubuntu/Debian-based systems
                    // Alternatively, use the appropriate package manager for other distros:
                    // sh 'sudo yum install -y coreutils'  // For RHEL/CentOS-based systems
                    // sh 'sudo dnf install -y coreutils'  // For Fedora-based systems
                }
            }
        }

        stage('Install Git') {
            steps {
                script {
                    // Install Git if it's not available
                    sh 'sudo apt-get update && sudo apt-get install -y git'  // For Ubuntu/Debian-based systems
                    // Alternatively, use the appropriate package manager for other distros:
                    // sh 'sudo yum install -y git'  // For RHEL/CentOS-based systems
                    // sh 'sudo dnf install -y git'  // For Fedora-based systems
                }
            }
        }

        stage('Install Maven') {
            steps {
                script {
                    // Install Maven if it's not available
                    sh 'sudo apt-get update && sudo apt-get install -y maven'  // For Ubuntu/Debian-based systems
                    // Alternatively, use the appropriate package manager for other distros:
                    // sh 'sudo yum install -y maven'  // For RHEL/CentOS-based systems
                    // sh 'sudo dnf install -y maven'  // For Fedora-based systems
                }
            }
        }

        stage('Check Shell') {
            steps {
                // This will print the shell being used in the Jenkins pipeline
                sh 'echo $SHELL'
                
                // Check environment variables
                sh 'echo "MAVEN_HOME: $MAVEN_HOME"'
                sh 'echo "PATH: $PATH"'
                sh 'echo "imageName: $imageName"'
                sh 'echo "version: $version"'
            }
        }

        stage("Build") {
            steps {
                echo "----------- Build Started ----------"
                sh 'mvn clean deploy -Dmaven.test.skip=true'
                echo "----------- Build Completed ----------"
            }
        }

        stage("Test") {
            steps {
                echo "----------- Unit Test Started ----------"
                sh 'mvn surefire-report:report'
                echo "----------- Unit Test Completed ----------"
            }
        }

        stage('SonarQube Analysis') {
            environment {
                scannerHome = tool 'blueberry-sonar-scanner'
            }
            steps {
                withSonarQubeEnv('blueberry-sonarqube-server') {
                    sh "${scannerHome}/bin/sonar-scanner"
                }
            }
        }

        stage("Quality Gate") {
            steps {
                script {
                    timeout(time: 1, unit: 'HOURS') {
                        def qg = waitForQualityGate()
                        if (qg.status != 'OK') {
                            error "Pipeline aborted due to quality gate failure: ${qg.status}"
                        }
                    }
                }
            }
        }

        stage("Jar Publish") {
            steps {
                script {
                    echo '<--------------- Jar Publish Started --------------->'
                    def server = Artifactory.newServer(url: registry + "/artifactory", credentialsId: "artfiact-cred")
                    def properties = "buildid=${env.BUILD_ID},commitid=${GIT_COMMIT}"
                    def uploadSpec = """{
                        "files": [
                            {
                                "pattern": "jarstaging/(*)",
                                "target": "maven-remote/{1}",
                                "flat": "false",
                                "props" : "${properties}",
                                "exclusions": [ "*.sha1", "*.md5"]
                            }
                        ]
                    }"""
                    def buildInfo = server.upload(uploadSpec)
                    buildInfo.env.collect()
                    server.publishBuildInfo(buildInfo)
                    echo '<--------------- Jar Publish Ended --------------->'
                }
            }
        }

        stage("Docker Build") {
            steps {
                script {
                    echo '<--------------- Docker Build Started --------------->'
                    app = docker.build(imageName + ":" + version)
                    echo '<--------------- Docker Build Ends --------------->'
                }
            }
        }

        stage("Docker Publish") {
            steps {
                script {
                    echo '<--------------- Docker Publish Started --------------->'
                    docker.withRegistry(registry, 'artfiact-cred') {
                        app.push()
                    }
                    echo '<--------------- Docker Publish Ended --------------->'
                }
            }
        }

        stage("Deploy") {
            steps {
                script {
                    echo '<--------------- Helm Deploy Started --------------->'
                    sh 'helm install ttrend ttrend-1.0.1.tgz'
                    echo '<--------------- Helm Deploy Ended --------------->'
                }
            }
        }
    }
}