---
- hosts: jenkins-slave
  become: true
  tasks:
    # Add repository for OpenJDK 21 using Adoptium or OpenJDK from PPA
    - name: Add OpenJDK 21 repository (if available in PPA)
      apt_repository:
        repo: "ppa:openjdk-r/ppa"
        state: present

    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install OpenJDK 21
      apt:
        name: openjdk-21-jdk
        state: present

    # Install Maven
    - name: Download Maven packages
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
        dest: /opt

    - name: Extract Maven packages
      unarchive:
        src: /opt/apache-maven-3.9.9-bin.tar.gz
        dest: /opt
        remote_src: yes

    - name: Set Maven environment variables
      lineinfile:
        path: /etc/environment
        regexp: "^MAVEN_HOME="
        line: "MAVEN_HOME=/opt/apache-maven-3.9.9"
        create: yes

    - name: Update PATH to include Maven
      lineinfile:
        path: /etc/environment
        regexp: "^PATH="
        line: "PATH=$PATH:/opt/apache-maven-3.9.9/bin"
        create: yes

    # Install Docker
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Give 777 permission on /var/run/docker.sock
      file:
        path: /var/run/docker.sock
        state: file
        mode: "0777"

    - name: Enable Docker service to start at boot time
      service:
        name: docker
        enabled: yes
